# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
    node: circleci/node@4.7

# Define the jobs we want to run for this project
jobs:
    build:
        resource_class: small
        working_directory: ~/app
        environment:
            IMAGE_NAME: adrielamoguis/stsweng-heroku-dcc
        docker:
            - image: circleci/buildpack-deps:stretch
        steps:
            - checkout
            - setup_remote_docker
            - run:
                  name: Build Docker Image
                  command: |
                      docker build -t $IMAGE_NAME:latest .
            - run:
                  name: Push Docker Image
                  command: |
                      echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                      docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CIRCLE_SHA1
                      docker push $IMAGE_NAME:$CIRCLE_SHA1
    test:
        environment:
            IMAGE_NAME: adrielamoguis/stsweng-heroku-dcc
        resource_class: small
        docker:
            - image: circleci/buildpack-deps:stretch
        steps:
            - setup_remote_docker
            - run:
                  name: Pull Latest Docker Image
                  command: |
                      echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                      docker pull $IMAGE_NAME:latest
            - run:
                  name: Run all npm test scripts
                  command: |
                      npm run test

# Orchestrate our job run sequence
workflows:
    build_and_test:
        jobs:
            - build
            - test:
                  requires:
                      - build
